# Generated by Django 5.1.7 on 2025-03-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='is_farmer',
            field=models.BooleanField(default=True),
        ),
    ]
